#!/usr/bin/env pandoc-lua
--- perevir – a test tool for pandoc transformations.
--
-- Copyright: © 2024 Albert Krewinkel <albert+pandoc@tarleb.com>
-- License: MIT

local perevir = require 'perevir'

local opts = perevir.parse_args(arg)
perevir.do_checks(opts)
