name: CI

on:
  # Run on all pull requests that change code.
  pull_request:
    paths-ignore:
      - 'README.md'
      - LICENSE
      - .editorconfig
  # Run every time a code change is pushed.
  push:
    paths-ignore:
      - 'README.md'
      - LICENSE
      - .editorconfig
  # Test if things still work each Tuesday morning at 5:39 UTC.
  # This way we will catch incompatible pandoc changes in a timely
  # manner.
  schedule:
    # At 5:39am each Tuesday
    - cron: '39 5 * * 2'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: |
          # Use docker image with current release.
          make test \
            PANDOC="docker run --rm --volume $(pwd):/data \
              --user $(id -u):$(id -g) pandoc/core:latest"
